config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  get 'tos', to: 'welcome#tos', as: 'tos'
  get 'help', to: 'welcome#help', as: 'help'
  get 'privacy_policy', to: 'welcome#privacy_policy', as: 'privacy_policy'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :users do
    resources :subscriptions, only: %i(index) ,controller: "users/subscriptions"
  end
  
  resource :retirements
  
  resources :users, only: %i(show)
  resources :sessions, only: %i(new create destroy)
  resources :welcome, only: %i(index)
  resources :subscriptions, only: %i(index new create edit update destroy)

  namespace :subscriptions do
    resources :status, only: %i(edit update)
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/subscription.rb
# frozen_string_literal: true

class Subscription < ApplicationRecord
  validates :name, length: { maximum: 50 }, presence: true
  validates :payment_date, presence: true
  validates :fee, length: { maximum: 7 }, presence: true
  validates :my_account_url, length: { maximum: 200 }
  validates :subscribed, inclusion: { in: [true, false] }
  validates :cycle, presence: true
  validate :payment_date_before_this_month

  belongs_to :user

  def calc_next_payment_date
    duration = calc_duration

    if (duration % cycle).zero?
      # 経過月数と周期の余りが0の場合は経過月数で次回お支払日を算出
      payment_date.since(duration.month)
    elsif duration > cycle
      # 経過月数が周期より大きかったら経過月数と周期を割った切り上げ結果に周期をかけて次回お支払日を算出
      duration = (duration.to_f / cycle).ceil
      payment_date.since((duration * cycle).month)
    else
      payment_date.since(cycle.month)
    end
  end

  private

  def calc_duration
    # お支払基準日からの経過を本日との差分で算出
    today = Date.current
    # 年の経過の差分を算出
    year_duration = today.year - payment_date.year
    # 月の経過の差分を算出
    month_duration = today.month - payment_date.month
    # 年を月単位に変換し、合計の経過月数を算出
    duration = (year_duration * 12) + month_duration

    if today >= payment_date && cycle == 1
      duration += 1
    elsif duration.zero?
      duration = cycle
    else
      duration
    end
    duration
  end

  def payment_date_before_this_month
    return if payment_date.blank?

    return unless payment_date.year >= Date.current.year && payment_date.month > Date.current.month

    errors.add(:payment_date, 'お支払基準日は今月以前の直近の日付を指定してください。')
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  after_save :create_id_digest
  validates :uid, uniqueness: { scope: :provider }

  has_many :subscriptions, dependent: :destroy

  def self.from_omniauth(auth_hash)
    provider = auth_hash[:provider]
    uid = auth_hash[:uid]
    User.where(provider:, uid:).first_or_initialize
  end

  def to_param
    id_digest
  end

  private

  def create_id_digest
    return unless id_digest.nil?

    new_digest = Digest::MD5.hexdigest(id.to_s)
    update_column(:id_digest, new_digest)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate
  helper_method :logged_in?, :current_user

  private

  def logged_in?
    !!current_user
  end

  def current_user
    return unless session[:user_id]

    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def authenticate
    return if logged_in?

    redirect_to root_path, notice: 'ログインしてください'
  end
end

app/controllers/retirements_controller.rb
# frozen_string_literal: true

class RetirementsController < ApplicationController
  def new; end

  def create
    return unless current_user.destroy

    reset_session
    redirect_to root_path, notice: '退会が完了しました。'
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  skip_before_action :authenticate, only: :create

  def new; end

  def create
    auth_hash = request.env['omniauth.auth']
    user = User.from_omniauth(auth_hash)
    if user.save
      session[:user_id] = user.id
      redirect_to subscriptions_path, notice: 'ログインしました。'
    else
      redirect_to root_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'ログアウトしました。'
  end
end

app/controllers/subscriptions/status_controller.rb
# frozen_string_literal: true

module Subscriptions
  class StatusController < ApplicationController
    before_action :set_subscription, only: %i[edit update]

    def edit; end

    def update
      @subscription.update!(subscription_params)
      redirect_to root_path, notice: "サブスクリプション「#{@subscription.name}」を編集しました。"
    end

    private

    def subscription_params
      params.require(:subscription).permit(:name, :payment_date, :fee, :my_account_url, :subscribed, :cycle, :user_id)
    end

    def set_subscription
      @subscription = Subscription.find(params[:id])
    end
  end
end

app/controllers/subscriptions_controller.rb
# frozen_string_literal: true

class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: %i[edit update destroy]

  def index
    @subscriptions = current_user.subscriptions.order(created_at: :DESC)
  end

  def show; end

  def new
    @subscription = Subscription.new
  end

  def create
    @subscription = current_user.subscriptions.new(subscription_params)
    if @subscription.save
      redirect_to root_path, notice: "サブスクリプション「#{@subscription.name}」を登録しました。"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @subscription.update(subscription_params)
      redirect_to root_path, notice: "サブスクリプション「#{@subscription.name}」を編集しました。"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @subscription.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: "サブスクリプション「#{@subscription.name}」を削除しました", status: :see_other }
    end
  end

  private

  def subscription_params
    params.require(:subscription).permit(:name, :payment_date, :fee, :my_account_url, :subscribed, :cycle, :user_id)
  end

  def set_subscription
    @subscription = Subscription.find(params[:id])
  end
end

app/controllers/users/calendars_controller.rb
# frozen_string_literal: true

module Users
  class CalendarsController < UsersController
    skip_before_action :authenticate, raise: false, only: :index

    def index
      respond_to do |format|
        format.ics do
          calendar = SubscriptionsInIcalFormatExporter.export_subscriptions(set_export)
          calendar.publish
          render plain: calendar.to_ical
        end
      end
    end

    private

    def set_expotr
      Subscription.where('subscribed = ?', true)
    end
  end
end

app/controllers/users/subscriptions_controller.rb
# frozen_string_literal: true

module Users
  class SubscriptionsController < ApplicationController
    skip_before_action :authenticate, raise: false, only: :index

    def index
      @subscriptions = set_export
    end

    private

    def set_export
      user = User.find_by!(id_digest: params[:user_id])
      user.subscriptions.where(subscribed: true)
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def show; end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  skip_before_action :authenticate

  def index
    redirect_to subscriptions_path if logged_in?
  end

  def help; end

  def tos; end

  def privacy_policy; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def default_meta_tags
    {
      site: 'サブスクの次回お支払日を管理 Subsc.mine',
      reverse: true,
      charset: 'utf-8',
      description: 'Subsc.mineは複数のサブスクリプションサービスを契約している人向けの、利用サブスク一覧ツールです。',
      og: {
        title: :title,
        type: 'website',
        site_name: 'Subsc.mine',
        description: :description,
        image: image_url('OGP.jpg'),
        url: 'https://subsc-mine.com/'
      },
      twitter: {
        card: 'summary_large_image',
        site: '@maimux2x'
      }
    }
  end
end

app/helpers/retirements_helper.rb
module RetirementsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name='viewport' content='width=device-width,initial-scale=1']
    = csrf_meta_tags
    = csp_meta_tag

    = display_meta_tags default_meta_tags
    = stylesheet_link_tag 'tailwind', 'inter-font', 'data-turbo-track': 'reload', defer: true
    = javascript_include_tag 'application', 'data-turbo-track': 'reload', defer: true, nonce: true
    = favicon_link_tag 'favicon.ico'
  body.flex.flex-col.min-h-screen
    - if logged_in?
      nav.nav-link.flex.justify-between.bg-stone-100.p-2.
        .flex.flex-shrink-0.text-white.mx-6.align-middle
          = link_to image_tag('logo2_1.png'), root_path, class: 'object-contain w-40 items-center'
        .flex.flex-shrink-0.text-brown.mx-6.align-middle
          = link_to 'ログアウト', signout_path, id: 'sign_out'
    - if flash.notice.present?
      .notification.w-screen.bg-cyan-100.border-l-4.border-cyan-500.text-cyan-700.p-4 = flash.notice
    main.container.m-auto
      .my-2.mx-3
        = yield
    footer.is-size-7.mt-auto
        = render 'shared/footer'

app/views/retirements/new.html.slim
= turbo_frame_tag 'retirements' do

  h1.font-semibold.text-xl アカウント削除確認画面

  p.my-4 ※アカウントを削除した場合、登録したサブスクリプションが全て削除されます。
  p.my-4 ※この操作は取り消せません。

  .flex.flex-initial.flex-wrap
    .flex.items-center.flex-shrink-0.mr-10
      = button_to 'アカウントを削除する', retirements_path, data: { turbo: 'false' },
        class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-5'
      .has-text-left.pt-5
    .flex.items-center.flex-shrink-0.mr-10
      = button_to 'キャンセル', subscriptions_path, method: :get, data: { turbo: 'false' },
        class: 'border bg-white-500 hover:bg-white-700 font-bold py-2 px-4 rounded mt-5'

app/views/shared/_footer.html.slim
footer.bg-stone-50.rounded-lg.shadow.m-4
  .w-full.mx-auto.max-w-screen-xl.p-4.md:flex.md:items-center.md:justify-between
    span.text-sm.text-gray-500.sm:text-center
      | © 2023
        |  maimux2x
      | . All Rights Reserved.
    ul.flex.flex-wrap.items-center.mt-3.text-sm.font-medium.text-gray-500sm:mt-0
      li.mr-4.hover:underline.md:mr-6
        = link_to 'https://github.com/maimux2x/subsc.mine'
          | GitHub
      li.mr-4.hover:underline.md:mr-6
        = link_to 'https://twitter.com/maimux2x'
          | Twitter
      li.mr-4.hover:underline.md:mr-6
        = link_to privacy_policy_path
          | プライバシーポリシー
      li.mr-4.hover:underline.md:mr-6
        = link_to tos_path
          | 利用規約
      li.mr-4.hover:underline.md:mr-6
        = link_to help_path
          | サービスガイド
      - if logged_in?
        li.mr-4.hover:underline.md:mr-6
          = link_to '退会する', new_retirements_path, data: { turbo_frame: 'retirements' }
          .hidden.fixed.overlay.top-0.left-0.w-screen.h-screen.bg-gray-700.bg-opacity-50.z-10 data-controller='modal' data-modal-target='modal' data-action='turbo:frame-load->modal#open turbo:submit-end->modal#close'
            .absolute.top-1/2.left-1/2.-translate-x-1/2.-translate-y-1/2.w-full.sm:w-max.sm:h-max.bg-white.p-10
              = turbo_frame_tag 'retirements'

app/views/subscriptions/_form.html.slim
.flex.justify-center
  =form_with model: subscription do |f|
    - if subscription.errors.any?
          ul.my-5.bg-red-100.border.border-red-400.text-red-700.px-4.py-3.w-max.rounded
            - subscription.errors.full_messages.each do |message|
              li.message-body.my-3 = message
    .my-5
      = f.label :name
      = f.text_field :name, placeholder: 'サブスクリプション名', class: 'block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-80'
    .mt-5.mb-2
      = f.label :payment_date
      = f.date_field :payment_date, class: 'block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-80'
    p.text-xs.text-zinc-500 ※次回支払い予定日の計算の基準日になります。
    p.text-xs.text-zinc-500 ※今月以前の日付で指定してください。
    .mt-5.mb-2
      = f.label :fee
      = f.number_field :fee, placeholder: 2000, class: 'block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-80'
    p.text-xs.text-zinc-500 ※半角数値で入力してください。
    .my-5
      = f.label :my_account_url
      = f.url_field :my_account_url, placeholder: 'https://example.com/user', class: 'block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-80'
    .my-5
      = f.label :subscribed, id: 'subscription_subscribed'
      = f.select :subscribed, [['停止中', false], ['継続中', true]], { selected: true },
        class: 'block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-24'
    .mt-5.mb-2
      = f.label :cycle, id: 'subscription_cycle'
      = f.select :cycle, [['1ヶ月毎', 1], ['2ヶ月毎', 2], ['3ヶ月毎', 3], ['6ヶ月毎', 6], ['12ヶ月毎', 12]], { include_blank: '選択してください' },
        class: 'block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-48'
    p.text-xs.text-zinc-500 ※サブスクリプションの更新周期を選択ください。
    .text-center.mt-5
      = f.submit nil, class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded'

app/views/subscriptions/edit.html.slim
h1.font-semibold.my-5.text-zinc-500.text-xl.text-center サブスクリプションの編集
.flex.flex-start
  .m-auto.underline
    = link_to '一覧へ戻る', subscriptions_path

= render partial: 'form', locals: { subscription: @subscription }

app/views/subscriptions/index.html.slim
- if @subscriptions.present?
  h1.font-semibold.mb-5.text-zinc-500.text-xl.text-center サブスクリプション一覧
  .flex.justify-center
    .flex.text-center.flex-shrink-0.mx-5
      .bg-blue-500.text-sm.md:text-base.hover:bg-blue-700.text-white.font-bold.py-2.px-4.w-40.rounded
          = button_to '新規登録', new_subscription_path, method: :get
    .flex.text-center.flex-shrink-0.mx-5
      .bg-blue-500.text-sm.md:text-base.hover:bg-blue-700.text-white.font-bold.py-2.px-4.w-40.rounded
          = button_to 'カレンダー連携', user_path(current_user), method: :get, data: { turbo_frame: 'calendar' }
    .hidden.fixed.overlay.top-0.left-0.w-screen.h-screen.bg-gray-700.bg-opacity-50.z-10 data-controller='modal' data-modal-target='modal' data-action='turbo:frame-load->modal#open turbo:submit-end->modal#close'
      .absolute.top-1/2.left-1/2.-translate-x-1/2.-translate-y-1/2.w-full.sm:w-max.sm:h-max.bg-white.p-10
        = turbo_frame_tag 'calendar'

- if @subscriptions.blank?
    .m-auto.text-center
      .md:w-9/12
      = image_tag 'logo2_3.png', class: 'm-auto'
      h1.my-5.font-bold.text-zinc-500.text-sm.md:text-2xl Subsc.mineでサブスクリプションの管理をしよう！
      p.mt-3.mb-8.text-xs.md:text-base まずは「新規登録」ボタンからあなたが利用中の<br>サブスクリプションを登録しましょう
      .bg-blue-500.text-sm.md:text-base.hover:bg-blue-700.text-white.font-bold.py-2.px-4.m-auto.rounded.w-fit
        = button_to 'サブスクリプションを新規登録', new_subscription_path, method: :get
      p.mt-8.mb-4.text-xs.md:text-base 登録したサブスクリプションのお支払い基準日と周期から<br>次回お支払い日を自動計算します
      p.my-4.text-xs.md:text-base サブスクリプションを登録したら「カレンダー連携」ボタンから<br>カレンダーアプリと次回お支払日の同期が可能になります
      p.my-4.text-xs.md:text-base カレンダー連携はサブスクリプションのステータスが<br>継続中のものが対象です
      .underline.text-xs.md:text-base
        = link_to help_path
          | サービスの詳しい使い方はこちら
- @subscriptions.each do |subscription|
  .my-5
    a.block.md:w-7/12.m-auto.p-6.bg-slate-50.border.border-gray-200.rounded-lg.shadow.hover:bg-gray-100
      .my-2
        table.bg-white.min-w-full.text-left.border
          tbody.leading-10.text-sm.md:text-base
              tr.border-b
                th.px-3 = Subscription.human_attribute_name(:name)
                td.px-3 = subscription.name
              tr.border-b
                th.px-3 = Subscription.human_attribute_name(:payment_date)
                td.px-3 = subscription.payment_date
              tr.border-b
                th.px-3 = '次回お支払日'
                td.px-3 = I18n.l subscription.calc_next_payment_date, format: :short
              tr.border-b
                th.px-3 = Subscription.human_attribute_name(:fee)
                td.px-3 = "#{subscription.fee}円"
              tr.border-b
                th.px-3 = Subscription.human_attribute_name(:my_account_url)
                td.px-3.underline = link_to subscription.my_account_url.to_s, subscription.my_account_url, target: :_blank, rel: 'noopener noreferrer'
              tr.border-b
                th.px-3 = Subscription.human_attribute_name(:subscribed)
                td.px-3 = subscription.subscribed_status
              tr.border-b
                th.px-3 = Subscription.human_attribute_name(:cycle)
                td.px-3 = "#{subscription.cycle}ヶ月毎"
        .flex.justify-center
          .mt-5.mx-2.text-sm.md:text-base.flex-wrap.bg-blue-500.hover:bg-blue-700.text-white.font-bold.py-2.px-2.rounded
            = button_to 'ステータス変更', edit_subscriptions_status_path(subscription), method: :get, data: { turbo_frame: 'status' }
          .hidden.fixed.m-auto.w-screen.h-screen.top-0.left-0.bg-gray-700/50.z-10 data-controller='modal' data-modal-target='modal' data-action='turbo:frame-load->modal#open turbo:submit-end->modal#close'
            .absolute.top-1/2.left-1/2.-translate-x-1/2.-translate-y-1/2.w-max.h-max.bg-white.p-10
              = turbo_frame_tag 'status'
          .mt-5.mx-2.text-sm.md:text-base.flex-wrap.bg-blue-500.hover:bg-blue-700.text-white.font-bold.py-2.px-2.rounded
            = button_to '編集', edit_subscription_path(subscription), method: :get
          .mt-5.mx-2.text-sm.md:text-base.flex-wrap.bg-blue-500.hover:bg-blue-700.text-white.font-bold.py-2.px-2.rounded
            = button_to '削除', subscription, method: :delete, data: { turbo_confirm: "サブスクリプション「#{subscription.name}」を削除します。よろしいですか?" }

app/views/subscriptions/new.html.slim
h1.font-semibold.my-5.text-zinc-500.text-xl.text-center サブスクリプションの新規登録

.flex.flex-start
  .m-auto.underline
    = link_to '一覧へ戻る', subscriptions_path

= render partial: 'form', locals: { subscription: @subscription }

app/views/subscriptions/status/_form.html.slim
=form_with model: subscription, local: true do |f|
  .my-5
    = f.label :subscribed, id: 'subscription_subscribed'
    = f.select :subscribed, [['停止中', false], ['継続中', true]], { selected: true },
        class: 'block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full'
  - unless @subscription.subscribed
    .my-5
      = f.label :payment_date
      = f.date_field :payment_date, class: 'block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full'
  .text-center.mt-5
    = f.submit nil, data: { turbo: 'false' }, class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 mr-5 rounded w-full'

= button_to 'キャンセル', subscriptions_path, method: :get, data: { turbo: 'false' },
class: 'border bg-white-500 hover:bg-white-700 font-bold py-2 px-4 mt-5 rounded w-full'

app/views/subscriptions/status/edit.html.slim
= turbo_frame_tag 'status' do
  h1.font-semibold.text-xl サブスクリプションの編集画面

  = render partial: 'form', locals: { subscription: @subscription }

app/views/users/show.html.slim
= turbo_frame_tag 'calendar' do
  h1.font-semibold.text-xl カレンダー連携
  ul.list-disc
    li.list-disc.my-1 iCalendar形式での連携が可能です。
    li.list-disc.my-1 次回お支払日をカレンダーアプリやGoogleカレンダーと同期してご利用いただけます。
    li.list-disc.my-1 ご利用のOSやアプリによってiCalendarの連携が動作しない場合があります。その場合はPCのGoogleカレンダーから連携をお試しください。
  .flex.flex-initial.flex-wrap
    .flex.items-center.flex-shrink-0.mr-10
      = link_to 'カレンダーと連携する', user_subscriptions_url(protocol: :webcal, format: :ics, user_id: current_user),
        class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-5'
    .flex.items-center.flex-shrink-0.mr-10
      = button_to '戻る', subscriptions_path, method: :get, data: { turbo: 'false' },
        class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-5'

app/views/users/subscriptions/index.ics.slim
- cal = Icalendar::Calendar.new
- @subscriptions.each do |subscription|
  - tzid = 'Asia/Tokyo'

  - cal.event do |e|
    - e.dtstart     = Icalendar::Values::DateTime.new subscription.calc_next_payment_date, { 'tzid' => tzid }
    - e.dtend       = Icalendar::Values::DateTime.new subscription.calc_next_payment_date, { 'tzid' => tzid }
    - e.summary     = subscription.name
    - e.uid         = "subscription#{subscription.id}"
    - e.sequence    = Time.now.to_i
= cal.to_ical

app/views/welcome/index.html.slim
block.max-w
  .max-w
    h1.text-center.font-bold.text-zinc-500.md:text-2xl 次のお支払日いつだっけ？を解決する
  .max-w
    = image_tag 'logo500px.png', class: 'm-auto w-6/12 md:w-3/12'
  .mt-10.mb-5
    .bg-blue-500.w-48.hover:bg-blue-700.text-white.font-bold.py-2.px-4.border.border-blue-700.rounded.m-auto
      = button_to 'Googleアカウントでログイン', '/auth/google_oauth2/', data: { turbo: 'false' }
  p.text-center.text-xs.text-zinc-500 ※上記ボタンをクリックすることで利用規約・プライバシーポリシーに同意したものとみなします。
  p.mb-10.text-center.text-xs.text-zinc-500 ※無料でご利用いただけます。
  .max-w.my-2
    h1.text-center.font-bold.text-zinc-500.md:text-2xl こんなことはありませんか？
  .max-w.my-3
    = image_tag 'IMG_20230509_141918.jpg', class: 'm-auto w-3/12 md:w-1/12'
  ul
    li.pt-3.text-center.text-xs.md:text-base 利用中のサブスクリプションの支払日が管理できていない
    li.pt-3.text-center.text-xs.md:text-base 無料期間中に解約しようとして、期間が過ぎていた
    li.pt-3.text-center.text-xs.md:text-base クレジットカードの変更を忘れて更新が止まってしまった
  .max-w.mt-12.mb-2
    h1.text-center.font-bold.text-zinc-500.md:text-2xl その課題、Subsc.mineで解決しましょう！
  .max-w.my-3
    = image_tag 'IMG_20230509_141950.jpg', class: 'm-auto w-3/12 md:w-1/12'
  ul
    li.pt-3.text-center.text-xs.md:text-base 利用しているサブスクリプションを一覧管理ができる
    li.pt-3.text-center.text-xs.md:text-base Subsc.mineに支払日と課金周期を登録すると次回以降を自動で計算
    li.pt-3.text-center.text-xs.md:text-base 次回支払い予定日をカレンダーアプリと同期できる